services:
  ai-chat: 
    build: .
    restart: always
    ports:
      - "8080:8080"
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maria123
      MYSQL_DATABASE: mariadb
      MYSQL_USER: maria
      MYSQL_PASSWORD: maria123
    ports:
      - "3306:3306"
    volumes:
      - db_ai_chat_data:/var/lib/mysql

volumes:
  db_ai_chat_data:
    driver: local